
DROP TABLE IF EXISTS command_execution;
DROP TABLE IF EXISTS payment;
DROP TABLE IF EXISTS order_item;
DROP TABLE IF EXISTS bot_order;
DROP TABLE IF EXISTS publication;
DROP TABLE IF EXISTS referral;
DROP TABLE IF EXISTS bot_command;
DROP TABLE IF EXISTS promo_code;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS bot_user;

CREATE TABLE bot_user (
    user_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id   BIGINT NOT NULL UNIQUE,
    username      VARCHAR(50) NOT NULL UNIQUE,
    role          VARCHAR(20) NOT NULL DEFAULT 'user',
    status        VARCHAR(20) NOT NULL DEFAULT 'active',
    registered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    balance       NUMERIC(10,2) NOT NULL DEFAULT 0,

    CONSTRAINT chk_bot_user_role
        CHECK (role IN ('user', 'admin')),

    CONSTRAINT chk_bot_user_status
        CHECK (status IN ('active', 'blocked')),

    CONSTRAINT chk_bot_user_balance
        CHECK (balance >= 0)
);

CREATE TABLE product (
    product_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    product_type VARCHAR(50) NOT NULL,
    price        NUMERIC(10,2) NOT NULL,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT chk_product_price
        CHECK (price >= 0)
);

CREATE TABLE promo_code (
    promo_code_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(50) NOT NULL UNIQUE,
    discount_type  VARCHAR(20) NOT NULL,
    discount_value NUMERIC(10,2) NOT NULL,
    starts_at      TIMESTAMP NOT NULL,
    ends_at        TIMESTAMP NOT NULL,

    CONSTRAINT chk_promo_discount_type
        CHECK (discount_type IN ('percent', 'fixed')),

    CONSTRAINT chk_promo_discount_value
        CHECK (
            (discount_type = 'percent' AND discount_value > 0 AND discount_value <= 100)
            OR
            (discount_type = 'fixed' AND discount_value > 0)
        ),

    CONSTRAINT chk_promo_dates
        CHECK (ends_at > starts_at)
);

CREATE TABLE bot_command (
    command_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    command_name VARCHAR(50) NOT NULL UNIQUE,
    description  TEXT,
    is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE referral (
    referral_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id   INTEGER NOT NULL,
    referred_id   INTEGER NOT NULL UNIQUE,
    reward_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_referral_referrer
        FOREIGN KEY (referrer_id)
        REFERENCES bot_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_referral_referred
        FOREIGN KEY (referred_id)
        REFERENCES bot_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_referral_not_self
        CHECK (referrer_id <> referred_id),

    CONSTRAINT chk_referral_reward
        CHECK (reward_amount >= 0)
);

CREATE TABLE publication (
    publication_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id      INTEGER NOT NULL,
    title          VARCHAR(150) NOT NULL,
    content        TEXT NOT NULL,
    tag_list       TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_publication_author
        FOREIGN KEY (author_id)
        REFERENCES bot_user(user_id)
        ON DELETE CASCADE
);

CREATE TABLE bot_order (
    order_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    promo_code_id INTEGER,
    status        VARCHAR(20) NOT NULL DEFAULT 'created',
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_amount  NUMERIC(10,2) NOT NULL DEFAULT 0,

    CONSTRAINT fk_bot_order_user
        FOREIGN KEY (user_id)
        REFERENCES bot_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_bot_order_promo_code
        FOREIGN KEY (promo_code_id)
        REFERENCES promo_code(promo_code_id)
        ON DELETE SET NULL,

    CONSTRAINT chk_bot_order_status
        CHECK (status IN ('created', 'paid', 'completed', 'cancelled')),

    CONSTRAINT chk_bot_order_total
        CHECK (total_amount >= 0)
);

CREATE TABLE order_item (
    order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      INTEGER NOT NULL,
    product_id    INTEGER NOT NULL,
    quantity      INTEGER NOT NULL,
    unit_price    NUMERIC(10,2) NOT NULL,
    line_total    NUMERIC(10,2) NOT NULL,

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
        REFERENCES bot_order(order_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id)
        REFERENCES product(product_id)
        ON DELETE RESTRICT,

    CONSTRAINT uq_order_item_order_product
        UNIQUE (order_id, product_id),

    CONSTRAINT chk_order_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_order_item_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_order_item_line_total
        CHECK (line_total >= 0)
);

CREATE TABLE payment (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INTEGER NOT NULL UNIQUE,
    amount     NUMERIC(10,2) NOT NULL,
    method     VARCHAR(30) NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'pending',
    paid_at    TIMESTAMP,

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
        REFERENCES bot_order(order_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_payment_amount
        CHECK (amount >= 0),

    CONSTRAINT chk_payment_method
        CHECK (method IN ('card', 'balance', 'crypto', 'manual')),

    CONSTRAINT chk_payment_status
        CHECK (status IN ('pending', 'paid', 'failed', 'refunded'))
);

CREATE TABLE command_execution (
    execution_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    command_id    INTEGER NOT NULL,
    executed_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    result_status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_command_execution_user
        FOREIGN KEY (user_id)
        REFERENCES bot_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_command_execution_command
        FOREIGN KEY (command_id)
        REFERENCES bot_command(command_id)
        ON DELETE CASCADE,

    CONSTRAINT chk_command_execution_status
        CHECK (result_status IN ('success', 'error'))
);
