
-- 1. Нормалізація таблиці product
CREATE TABLE IF NOT EXISTS product_type (
    product_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO product_type (name)
SELECT DISTINCT product_type
FROM product
WHERE product_type IS NOT NULL
ON CONFLICT (name) DO NOTHING;

ALTER TABLE product
ADD COLUMN IF NOT EXISTS product_type_id INTEGER;

UPDATE product p
SET product_type_id = pt.product_type_id
FROM product_type pt
WHERE p.product_type = pt.name;

ALTER TABLE product
ALTER COLUMN product_type_id SET NOT NULL;

ALTER TABLE product
ADD CONSTRAINT fk_product_product_type
FOREIGN KEY (product_type_id)
REFERENCES product_type(product_type_id);

ALTER TABLE product
DROP COLUMN product_type;



-- 2. Нормалізація таблиці bot_order

CREATE TABLE IF NOT EXISTS order_status (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO order_status (name)
SELECT DISTINCT status
FROM bot_order
WHERE status IS NOT NULL
ON CONFLICT (name) DO NOTHING;

ALTER TABLE bot_order
ADD COLUMN IF NOT EXISTS status_id INTEGER;

UPDATE bot_order o
SET status_id = os.status_id
FROM order_status os
WHERE o.status = os.name;

ALTER TABLE bot_order
ALTER COLUMN status_id SET NOT NULL;

ALTER TABLE bot_order
ADD CONSTRAINT fk_bot_order_status
FOREIGN KEY (status_id)
REFERENCES order_status(status_id);

ALTER TABLE bot_order
DROP CONSTRAINT IF EXISTS chk_bot_order_status;

ALTER TABLE bot_order
DROP COLUMN status;


-- 3. Нормалізація таблиці payment
CREATE TABLE IF NOT EXISTS payment_method (
    method_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS payment_status (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO payment_method (name)
SELECT DISTINCT method
FROM payment
WHERE method IS NOT NULL
ON CONFLICT (name) DO NOTHING;

INSERT INTO payment_status (name)
SELECT DISTINCT status
FROM payment
WHERE status IS NOT NULL
ON CONFLICT (name) DO NOTHING;

ALTER TABLE payment
ADD COLUMN IF NOT EXISTS method_id INTEGER;

ALTER TABLE payment
ADD COLUMN IF NOT EXISTS status_id INTEGER;

UPDATE payment p
SET method_id = pm.method_id
FROM payment_method pm
WHERE p.method = pm.name;

UPDATE payment p
SET status_id = ps.status_id
FROM payment_status ps
WHERE p.status = ps.name;

ALTER TABLE payment
ALTER COLUMN method_id SET NOT NULL;

ALTER TABLE payment
ALTER COLUMN status_id SET NOT NULL;

ALTER TABLE payment
ADD CONSTRAINT fk_payment_method
FOREIGN KEY (method_id)
REFERENCES payment_method(method_id);

ALTER TABLE payment
ADD CONSTRAINT fk_payment_status
FOREIGN KEY (status_id)
REFERENCES payment_status(status_id);

ALTER TABLE payment
DROP CONSTRAINT IF EXISTS chk_payment_method;

ALTER TABLE payment
DROP CONSTRAINT IF EXISTS chk_payment_status;

ALTER TABLE payment
DROP COLUMN method;

ALTER TABLE payment
DROP COLUMN status;



-- 4. Нормалізація таблиці publication


CREATE TABLE IF NOT EXISTS tag (
    tag_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS publication_tag (
    publication_id INTEGER NOT NULL,
    tag_id INTEGER NOT NULL,

    CONSTRAINT pk_publication_tag
        PRIMARY KEY (publication_id, tag_id),

    CONSTRAINT fk_publication_tag_publication
        FOREIGN KEY (publication_id)
        REFERENCES publication(publication_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_publication_tag_tag
        FOREIGN KEY (tag_id)
        REFERENCES tag(tag_id)
        ON DELETE CASCADE
);

INSERT INTO tag (name)
SELECT DISTINCT TRIM(tag_value)
FROM publication p
CROSS JOIN LATERAL unnest(string_to_array(p.tag_list, ',')) AS tag_value
WHERE p.tag_list IS NOT NULL
  AND TRIM(tag_value) <> ''
ON CONFLICT (name) DO NOTHING;

INSERT INTO publication_tag (publication_id, tag_id)
SELECT p.publication_id, t.tag_id
FROM publication p
CROSS JOIN LATERAL unnest(string_to_array(p.tag_list, ',')) AS tag_value
JOIN tag t ON t.name = TRIM(tag_value)
WHERE p.tag_list IS NOT NULL
  AND TRIM(tag_value) <> ''
ON CONFLICT DO NOTHING;

ALTER TABLE publication
DROP COLUMN tag_list;


SELECT 
    p.product_id,
    p.name AS product_name,
    pt.name AS product_type,
    p.price,
    p.is_active
FROM product p
JOIN product_type pt ON p.product_type_id = pt.product_type_id
ORDER BY p.product_id;


SELECT 
    o.order_id,
    u.username,
    os.name AS order_status,
    o.total_amount,
    o.created_at
FROM bot_order o
JOIN bot_user u ON o.user_id = u.user_id
JOIN order_status os ON o.status_id = os.status_id
ORDER BY o.order_id;



SELECT 
    p.payment_id,
    p.order_id,
    p.amount,
    pm.name AS payment_method,
    ps.name AS payment_status,
    p.paid_at
FROM payment p
JOIN payment_method pm ON p.method_id = pm.method_id
JOIN payment_status ps ON p.status_id = ps.status_id
ORDER BY p.payment_id;


SELECT 
    p.publication_id,
    p.title,
    t.name AS tag_name
FROM publication p
JOIN publication_tag pt ON p.publication_id = pt.publication_id
JOIN tag t ON pt.tag_id = t.tag_id
ORDER BY p.publication_id, t.name;